### ISSUE TITLE
Link to particular notebook

### ISSUE THREAD

**Issue by mrocklin** [binder-project/binder-web-prototype#9]
Migrated from https://github.com/binder-project/binder/issues/18

_Q: Is there a way to link to a particular notebook hosted on mybinder?_

A: from https://github.com/binder-project/binder/issues/18#issuecomment-139273270

Not yet but definitely possible! @andrewosh and I just sketched it out.

And the behavior we're imaging is something like this for linking to a notebook at the top level

```
mybinder.org/repo/user-name/repo-name/notebook-name.ipynb
```

this for linking to a sub-folder (presumably one with many notebooks)

```
mybinder.org/repo/user-name/repo-name/folder-name/
```

and this for a notebook in a sub-folder

```
mybinder.org/repo/user-name/repo-name/folder-name/notebook-name.ipynb
```

If that's not what you had in mind, definitely let us know what would be most intuitive!

**Comment by mrocklin** [comment]
@freeman-lab yes, this looks great to me

**Comment by freeman-lab** [comment]
This is now in production, let us know if you run into trouble @mrocklin ! Thanks again for the suggestion.
